#!/bin/sh

set -x

while read OLDREV NEWREV REFNAME ; do
    author_name=$(git show --pretty=oneline --pretty=format:%an $NEWREV | head -n1)
    echo "Commit from $author_name"
    if [ $author_name != "lain" ]; then
        echo "Forbidden author"
        exit 1
    fi
done

